---
- name: Deploy Portainer on Docker Swarm
  hosts: swarm_leader
  become: true
  tasks:
    - name: Deploy Portainer on Docker Swarm
      shell: >
        docker service create
        --name portainer
        --publish 9000:9000
        --replicas=1
        --constraint 'node.role==manager'
        --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock
        portainer/portainer-ce
      args:
        creates: /tmp/portainer_deployed
      tags: portainer
